"""
Integration tests for agent with LLM providers

Tests cover:
- Full agent run with Gemini (requires API key)
- Agent fallback when primary provider fails
- Agent with no LLM providers (deterministic fallback)

Requirements: 9.1, 9.2, 9.3, 9.4, 9.5
"""

import pytest
import os
from unittest.mock import patch, Mock

from backend.agents.graph import GRAPH
from backend.llm import get_manager
from backend.llm.exceptions import AllProvidersFailedError


# ============================================================================
# Test Fixtures
# ============================================================================

@pytest.fixture
def sample_instruction():
    """Sample instruction for agent testing"""
    return "prepare stability pull list for week 12"


@pytest.fixture
def mock_gemini_success():
    """Mock successful Gemini provider"""
    mock_provider = Mock()
    mock_provider.is_available.return_value = True
    mock_provider.chat.return_value = '''
    {
        "plan": [
            {"tool": "lims.create_pull_list", "args": {"week": "12"}},
            {"tool": "sheets.append_rows", "args": {}},
            {"tool": "jira.create_issue", "args": {
                "summary": "Weekly stability pulls prepared (W12)",
                "labels": ["stability", "week12"],
                "idem_key": "stability-week-12"
            }},
            {"tool": "mailer.draft_email", "args": {
                "to": ["qa@example.com"],
                "subject": "Week 12 stability pull list",
                "body": "See table below"
            }}
        ]
    }
    '''
    mock_provider.name = 'gemini'
    return mock_provider


@pytest.fixture
def mock_openrouter_success():
    """Mock successful OpenRouter provider"""
    mock_provider = Mock()
    mock_provider.is_available.return_value = True
    mock_provider.chat.return_value = '''
    {
        "plan": [
            {"tool": "lims.create_pull_list", "args": {"week": "12"}},
            {"tool": "sheets.append_rows", "args": {}},
            {"tool": "jira.create_issue", "args": {
                "summary": "Weekly stability pulls prepared (W12)",
                "labels": ["stability", "week12"],
                "idem_key": "stability-week-12"
            }},
            {"tool": "mailer.draft_email", "args": {
                "to": ["qa@example.com"],
                "subject": "Week 12 stability pull list",
                "body": "See table below"
            }}
        ]
    }
    '''
    mock_provider.name = 'openrouter'
    return mock_provider


# ============================================================================
# Integration Tests
# ============================================================================

class TestAgentWithGemini:
    """Integration tests for agent with Gemini provider"""
    
    @pytest.mark.skipif(
        not os.getenv('GEMINI_API_KEY'),
        reason="Requires GEMINI_API_KEY environment variable"
    )
    def test_full_agent_run_with_real_gemini(self, sample_instruction):
        """
        Test full agent run with real Gemini API
        
        This test requires a valid GEMINI_API_KEY environment variable.
        It verifies end-to-end functionality with a real LLM provider.
        
        Requirements: 9.1, 9.3, 9.4
        """
        # Run agent with real Gemini
        result = GRAPH.invoke({"instruction": sample_instruction})
        
        # Verify agent completed successfully
        assert "plan" in result
        assert "steps" in result
        assert "review" in result
        assert "llm_provider" in result
        
        # Verify plan was generated
        assert len(result["plan"]) > 0
        
        # Verify steps were executed
        assert len(result["steps"]) > 0
        
        # Verify LLM provider was tracked
        assert result["llm_provider"] in ["gemini", "deterministic"]
        
        # Verify review was performed
        assert "passed" in result["review"]
    
    def test_agent_with_mocked_gemini_success(self, sample_instruction, mock_gemini_success):
        """
        Test agent with mocked successful Gemini provider
        
        Verifies that agent can successfully generate and execute a plan
        when Gemini provider is available and working.
        
        Requirements: 9.1, 9.3
        """
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class:
            # Setup mock
            mock_gemini_class.return_value = mock_gemini_success
            
            # Force manager reload to pick up mock
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify plan was generated by LLM
            assert "plan" in result
            assert len(result["plan"]) == 4
            
            # Verify expected tools in plan
            tools = [step["tool"] for step in result["plan"]]
            assert "lims.create_pull_list" in tools
            assert "sheets.append_rows" in tools
            assert "jira.create_issue" in tools
            assert "mailer.draft_email" in tools
            
            # Verify steps were executed
            assert "steps" in result
            assert len(result["steps"]) == 4
            
            # Verify LLM provider was tracked
            assert result.get("llm_provider") == "gemini"
            
            # Verify review was performed
            assert "review" in result


class TestAgentFallback:
    """Integration tests for agent fallback behavior"""
    
    def test_agent_fallback_when_primary_fails(self, sample_instruction, mock_openrouter_success):
        """
        Test agent falls back to secondary provider when primary fails
        
        Verifies that when Gemini (primary) fails, the agent automatically
        falls back to OpenRouter (secondary) and completes successfully.
        
        Requirements: 9.1, 9.2, 9.3
        """
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class, \
             patch('backend.llm.manager.OpenRouterProvider') as mock_openrouter_class:
            
            # Gemini fails
            mock_gemini_fail = Mock()
            mock_gemini_fail.is_available.return_value = True
            mock_gemini_fail.chat.side_effect = Exception("Gemini unavailable")
            mock_gemini_class.return_value = mock_gemini_fail
            
            # OpenRouter succeeds
            mock_openrouter_class.return_value = mock_openrouter_success
            
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify plan was generated (by fallback provider)
            assert "plan" in result
            assert len(result["plan"]) > 0
            
            # Verify steps were executed
            assert "steps" in result
            
            # Verify fallback provider was used
            assert result.get("llm_provider") == "openrouter"
            
            # Verify agent completed successfully despite primary failure
            assert "review" in result
    
    def test_agent_fallback_on_rate_limit(self, sample_instruction, mock_openrouter_success):
        """
        Test agent falls back when primary provider hits rate limit
        
        Verifies that rate limits trigger fallback to next provider.
        
        Requirements: 9.1, 9.2
        """
        from backend.llm.exceptions import RateLimitError
        
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class, \
             patch('backend.llm.manager.OpenRouterProvider') as mock_openrouter_class:
            
            # Gemini hits rate limit
            mock_gemini_fail = Mock()
            mock_gemini_fail.is_available.return_value = True
            mock_gemini_fail.chat.side_effect = RateLimitError("Rate limit exceeded")
            mock_gemini_class.return_value = mock_gemini_fail
            
            # OpenRouter succeeds
            mock_openrouter_class.return_value = mock_openrouter_success
            
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify fallback occurred
            assert "plan" in result
            assert result.get("llm_provider") == "openrouter"
            
            # Verify agent completed successfully
            assert "steps" in result
            assert "review" in result


class TestAgentDeterministicFallback:
    """Integration tests for deterministic fallback when no LLM providers available"""
    
    def test_agent_with_no_llm_providers(self, sample_instruction):
        """
        Test agent uses deterministic fallback when no LLM providers configured
        
        Verifies backward compatibility: when no LLM providers are available,
        the agent falls back to deterministic planning logic.
        
        Requirements: 9.1, 9.2, 9.3
        """
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class, \
             patch('backend.llm.manager.OpenRouterProvider') as mock_openrouter_class, \
             patch('backend.llm.manager.OllamaProvider') as mock_ollama_class, \
             patch('backend.llm.manager.LocalLLMProvider') as mock_local_class:
            
            # All providers unavailable
            for mock_class in [mock_gemini_class, mock_openrouter_class, 
                              mock_ollama_class, mock_local_class]:
                mock_provider = Mock()
                mock_provider.is_available.return_value = False
                mock_class.return_value = mock_provider
            
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify deterministic plan was generated
            assert "plan" in result
            assert len(result["plan"]) == 4
            
            # Verify deterministic plan structure
            tools = [step["tool"] for step in result["plan"]]
            assert "lims.create_pull_list" in tools
            assert "sheets.append_rows" in tools
            assert "jira.create_issue" in tools
            assert "mailer.draft_email" in tools
            
            # Verify week was extracted correctly
            lims_step = next(s for s in result["plan"] if s["tool"] == "lims.create_pull_list")
            assert lims_step["args"]["week"] == "12"
            
            # Verify idem_key in jira step
            jira_step = next(s for s in result["plan"] if s["tool"] == "jira.create_issue")
            assert jira_step["args"]["idem_key"] == "stability-week-12"
            
            # Verify steps were executed
            assert "steps" in result
            assert len(result["steps"]) == 4
            
            # Verify deterministic provider was tracked
            assert result.get("llm_provider") == "deterministic"
            
            # Verify review was performed
            assert "review" in result
    
    def test_agent_with_all_providers_failing(self, sample_instruction):
        """
        Test agent uses deterministic fallback when all LLM providers fail
        
        Verifies that when all configured providers fail (not just unavailable),
        the agent gracefully falls back to deterministic planning.
        
        Requirements: 9.1, 9.2
        """
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class, \
             patch('backend.llm.manager.OpenRouterProvider') as mock_openrouter_class:
            
            # All providers fail with errors
            for mock_class in [mock_gemini_class, mock_openrouter_class]:
                mock_provider = Mock()
                mock_provider.is_available.return_value = True
                mock_provider.chat.side_effect = Exception("Provider error")
                mock_class.return_value = mock_provider
            
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify deterministic fallback was used
            assert "plan" in result
            assert len(result["plan"]) == 4
            
            # Verify deterministic provider was tracked
            assert result.get("llm_provider") == "deterministic"
            
            # Verify agent completed successfully
            assert "steps" in result
            assert "review" in result
    
    def test_deterministic_fallback_week_extraction(self):
        """
        Test deterministic fallback correctly extracts week numbers
        
        Verifies various week number formats are handled correctly.
        
        Requirements: 9.1
        """
        test_cases = [
            ("prepare stability pull list for week 12", "12"),
            ("stability pulls for 2024-w05", "5"),
            ("week 52 stability", "52"),
            ("no week specified", None),  # Should use current week
        ]
        
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class:
            # No providers available
            mock_provider = Mock()
            mock_provider.is_available.return_value = False
            mock_gemini_class.return_value = mock_provider
            
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            for instruction, expected_week in test_cases:
                result = GRAPH.invoke({"instruction": instruction})
                
                # Verify plan was generated
                assert "plan" in result
                
                # Check week in lims step
                lims_step = next(s for s in result["plan"] if s["tool"] == "lims.create_pull_list")
                
                if expected_week:
                    assert lims_step["args"]["week"] == expected_week
                else:
                    # Should have some week number (current week)
                    assert "week" in lims_step["args"]
                    assert lims_step["args"]["week"].isdigit()


class TestAgentAPIEndpoints:
    """Integration tests for agent API endpoints with LLM"""
    
    def test_agent_run_endpoint_tracks_provider(self, sample_instruction, mock_gemini_success):
        """
        Test /agent/run endpoint tracks which LLM provider was used
        
        Verifies that the API endpoint correctly captures and returns
        the LLM provider information for audit logging.
        
        Requirements: 9.3, 9.4, 9.5
        """
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class:
            # Setup mock
            mock_gemini_class.return_value = mock_gemini_success
            
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent through graph (simulating API endpoint)
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify provider tracking in result
            assert "llm_provider" in result
            assert result["llm_provider"] == "gemini"
            
            # This would be passed to db.add_audit() in the actual endpoint
            # Verify the data structure is correct for audit logging
            assert isinstance(result["llm_provider"], str)
    
    def test_agent_maintains_api_compatibility(self, sample_instruction):
        """
        Test agent maintains backward compatible API response format
        
        Verifies that the agent response structure remains compatible
        with existing API consumers.
        
        Requirements: 9.3, 9.4
        """
        with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class:
            # No providers available - use deterministic
            mock_provider = Mock()
            mock_provider.is_available.return_value = False
            mock_gemini_class.return_value = mock_provider
            
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify all expected fields are present
            assert "instruction" in result
            assert "plan" in result
            assert "steps" in result
            assert "review" in result
            assert "iter" in result
            
            # Verify new field doesn't break existing structure
            assert "llm_provider" in result
            
            # Verify plan structure
            for step in result["plan"]:
                assert "tool" in step
                assert "args" in step
            
            # Verify steps structure
            for step in result["steps"]:
                assert "id" in step
                assert "action" in step
                # Either result or error should be present
                assert "result" in step or "error" in step
            
            # Verify review structure
            assert "passed" in result["review"]


class TestAgentDockerCompatibility:
    """Integration tests for Docker deployment compatibility"""
    
    def test_agent_with_docker_environment_variables(self, sample_instruction):
        """
        Test agent works with Docker-style environment variable configuration
        
        Verifies that the agent can be configured through environment
        variables as specified in docker-compose.yml.
        
        Requirements: 9.4, 9.5
        """
        # Simulate Docker environment
        with patch.dict(os.environ, {
            'LLM_PROVIDER': 'gemini',
            'GEMINI_API_KEY': 'test-key',
            'LLM_FALLBACK_CHAIN': 'gemini,openrouter',
            'LLM_MAX_RETRIES': '3',
            'LLM_TIMEOUT': '60'
        }):
            with patch('backend.llm.manager.GeminiProvider') as mock_gemini_class:
                # Setup mock
                mock_provider = Mock()
                mock_provider.is_available.return_value = True
                mock_provider.chat.return_value = '{"plan": []}'
                mock_gemini_class.return_value = mock_provider
                
                # Force manager reload to pick up environment
                from backend.llm import _manager_instance
                _manager_instance[0] = None
                
                # Verify manager can be initialized
                manager = get_manager()
                assert manager is not None
                
                # Verify configuration was loaded
                assert manager.config.primary_provider == 'gemini'
                assert 'gemini' in manager.config.fallback_chain
    
    def test_agent_without_llm_env_vars_uses_deterministic(self, sample_instruction):
        """
        Test agent gracefully handles missing LLM environment variables
        
        Verifies that when no LLM providers are configured via environment
        variables, the agent falls back to deterministic mode.
        
        Requirements: 9.1, 9.5
        """
        # Simulate environment with no LLM configuration
        with patch.dict(os.environ, {}, clear=True):
            # Force manager reload
            from backend.llm import _manager_instance
            _manager_instance[0] = None
            
            # Run agent
            result = GRAPH.invoke({"instruction": sample_instruction})
            
            # Verify deterministic fallback was used
            assert "plan" in result
            assert result.get("llm_provider") == "deterministic"
            
            # Verify agent completed successfully
            assert "steps" in result
            assert "review" in result
